package com.qoid.bennu

object ErrorCode {
  val nameInvalid = "nameInvalid"
  val nameDuplicate = "nameDuplicate"
  val passwordInvalid = "passwordInvalid"
  val contextAliasIidInvalid = "contextAliasIidInvalid"
  val typeInvalid = "typeInvalid"
  val queryInvalid = "queryInvalid"
  val historicalStandingInvalid = "historicalStandingInvalid"
  val permissionDenied = "permissionDenied"
  val importAgentFailed = "importAgentFailed"
  val authenticationIdInvalid = "authenticationIdInvalid"
  val authenticationFailed = "authenticationFailed"
  val timeoutMillisInvalid = "timeoutMillisInvalid"
  val byteCountInvalid = "byteCountInvalid"
  val routeInvalid = "routeInvalid"
  val unexpectedError = "unexpectedError"
  val unsupportedMessage = "unsupportedMessage"
  val unsupportedResponseMessage = "unsupportedResponseMessage"
  val contentTypeInvalid = "contentTypeInvalid"
  val dataInvalid = "dataInvalid"
  val labelIidsInvalid = "labelIidsInvalid"
  val profileNameInvalid = "profileNameInvalid"
  val profileNameProfileImageInvalid = "profileNameProfileImageInvalid"
}
